# Generated by Django 5.2.5 on 2025-09-14 10:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('description', models.TextField()),
                ('thumbnail', models.URLField(default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQgLNLbFmOl-wuybKGc6IrdKYGPxe62xr-wYA&s')),
                ('category', models.CharField(choices=[('men', 'Men'), ('women', 'Women')], default='men', max_length=20)),
                ('comment', models.TextField()),
                ('rating', models.IntegerField(choices=[(5, '5'), (4, '4'), (3, '3'), (2, '2'), (1, '1')], default=5)),
                ('is_featured', models.BooleanField()),
                ('likes', models.IntegerField(default=0)),
            ],
        ),
    ]
